# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
reviews:
  path_filters:
    - "!**/*.mod"
    - "!**/*.sum"
    - "!docs/docs/cmd/*.md"
  auto_review:
    enabled: true